### ISSUE TITLE
Please explain how to use it

### ISSUE THREAD

**Issue by FastNinja** [cucumber/cucumber-html#37]
Hi guys,
I must be really stupid - but I couldn't figure out how to actually  use it.

I Use Cucumber JS to run BDD tests. I can product .json or text output files from the test runner.

My assumptions is that I can feed these .json file to Cucumber-HTML and get a valid HTML report.
How?

**Comment by mucsi96** [comment]
+1

**Comment by maxmeyer** [comment]
@mucsi96 Please use the "new style" reaction button of "github".

**Comment by maxmeyer** [comment]
You might want to have a look at https://github.com/cucumber/cucumber-pretty-formatter

**Comment by mucsi96** [comment]
Thanks!

**Comment by mucsi96** [comment]
@maxmeyer cucmber-pretty-formatter currently does not support JS. I created an issue for that https://github.com/cucumber/cucumber-pretty-formatter/issues/4

**Comment by brasmusson** [comment]
@FastNinja This project is not a (standalone) tool to produce html-reports from json-reports. You are probably thinking of [cucumber-reporting](https://github.com/damianszczepanik/cucumber-reporting) (for Jenkins) or [cucumber-sandwich](https://github.com/damianszczepanik/cucumber-sandwich). Neither of these tools are developed or maintained by the team of [Cucumber projects](https://github.com/cucumber).

Cucumber-JVM has integrated this project in its html-formatter. Cucumber-JS has not done it (yet), see https://github.com/cucumber/cucumber-js/issues/28.

I close this since this is an issue tracker and not a [support forum](https://cucumber.io/support).

**Comment by FastNinja** [comment]
@brasmusson 
My confusion came from the fact that on the main page of Cucumber-HTML it clams

> Cucumber-HTML is a cross-platform HTML formatter **for all the Cucumber implementations**. It's currently only used by Cucumber-JVM **and Cucumber.js**

Probably you will want to update front page then? is it a module that has to be used by other Cucumber implmenentations?

**Comment by brasmusson** [comment]
@FastNinja Yes, this project is to be used from within other Cucumber implementations.
